name: PR Comment Check

on:
  issue_comment:
    types: [created]

jobs:
  check_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check if comment starts with the specified username
        run: |
          COMMENT_BODY=$(jq --raw-output .comment.body "$GITHUB_EVENT_PATH")
          if [[ "$COMMENT_BODY" == <username>* ]]; then
            echo "Triggering REST API request because the comment starts with <username>"
            curl -X POST https://example.com/api-endpoint -d '{"username": "<username>", "comment": "'"$COMMENT_BODY"'"}'
          else
            echo "No match for username in comment."
          fi
