name: Link Discord Workflow

on:
  issues:
    types:
      - opened
      - edited

jobs:
  link-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Issue has the label 'Link Discord'
        if: contains(github.event.issue.labels.*.name, 'Link Discord')
        run: |
          # Extrahiere den Titel des Issues
          issue_title="${{ github.event.issue.title }}"
          
          # Überprüfen, ob der Titel mit 'username: ' beginnt
          if [[ "$issue_title" =~ ^username:\ (.*) ]]; then
            # Extrahiere Discord und GitHub Benutzernamen
            discord_username="${BASH_REMATCH[1]}"
            github_username="${{ github.event.issue.user.login }}"

            # API-Aufruf senden
            curl -X POST \
                 -H "Content-Type: application/json" \
                 -d '{"discord_username": "'"$discord_username"'", "github_username": "'"$github_username"'"}' \
                 https://deine-api-endpoint.com/link-discord
          else
            echo "Titel des Issues entspricht nicht dem erwarteten Format."
          fi
