name: Link Discord Workflow

on:
  issues:
    types:
      - opened
      - edited

jobs:
  link-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Issue has the label 'Link Discord'
        if: contains(github.event.issue.labels.*.name, 'Link Discord')
        run: |
          # Extract the issue title
          issue_title="${{ github.event.issue.title }}"
          
          # Check if the title starts with 'username: '
          if [[ "$issue_title" =~ ^username:\ (.*) ]]; then
            # Extract Discord and GitHub usernames
            discord_username="${BASH_REMATCH[1]}"
            github_username="${{ github.event.issue.user.login }}"

            # Retrieve environment variables
            discord_token="${{ secrets.DISCORD_DM_SECRET }}"
            dm_url="${{ secrets.DM_URL }}"

            # Make the API call
            curl -X POST \
                 -H "Content-Type: application/json" \
                 -H "Authorization: Bearer $discord_token" \
                 -d '{"discord_username": "'"$discord_username"'", "github_username": "'"$github_username"'"}' \
                 "$dm_url"
            
            # Close the issue using GitHub API
            issue_number="${{ github.event.issue.number }}"
            github_token="${{ secrets.GITHUB_TOKEN }}"

            curl -X PATCH \
                 -H "Authorization: Bearer $github_token" \
                 -H "Content-Type: application/json" \
                 -d '{"state": "closed"}' \
                 "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number"
          else
            echo "Issue title does not match the expected format."
          fi
