name: Validate JSON

on:
  pull_request:
    paths:
      - 'cosmetics/**/*.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq and jsonschema
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3-pip
          pip3 install jsonschema

      - name: Validate JSON files
        run: |
          SCHEMA_PATH="./checks/block-model.schema.json"
          for file in $(find . -name "*.json"); do
            echo "Validating $file"
            # Prüft, ob die JSON-Datei überhaupt syntaktisch korrekt ist
            jq empty "$file" || exit 1
            # Validierung gegen das Schema
            python3 -m jsonschema -i "$file" "$SCHEMA_PATH" || exit 1
          done
