name: Validate JSON

on:
  pull_request:
    paths:
      - '**/*.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq and jsonschema
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3-pip
          pip3 install jsonschema

      - name: Validate JSON file
        run: |
          SCHEMA_URL="https://raw.githubusercontent.com/OnThePixel-net/Cosmetics/refs/heads/main/checks/validate-json.yml"
          for file in $(find . -name "*.json"); do
            echo "Validating $file"
            jq empty "$file" || exit 1
            curl -sSL "$SCHEMA_URL" -o schema.json
            python3 -m jsonschema -i "$file" schema.json || exit 1
          done
